baseurl = "https://example.org/"
languageCode = "en-us"
title = "Iconem"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Iconem"

		[params.navigation.links]
			projects = "Projects"
			map  = "Map"
			about = "About"
			contact   = "Contact"


	# Home section
	[params.home]
		slogan     = "Explore human heritage"
		draw = "img/home/home_draw.png"

		[[params.home.social]]
            id = "tumblr"
            icon = "img/home/social/tumblr.png"
            icon_active = "img/home/social/tumblr_active.png"
            link = "http://iconem.tumblr.com/"

		[[params.home.social]]
            id = "facebook"
            icon = "img/home/social/facebook.png"
            icon_active = "img/home/social/facebook_active.png"
            link = "https://fr-fr.facebook.com/Iconem.corp/"

        [[params.home.social]]
            id = "twitter"
            icon = "img/home/social/twitter.png"
            icon_active = "img/home/social/twitter_active.png"
            link = "https://twitter.com/iconem"

        [[params.home.social]]
            id = "youtube"
            icon = "img/home/social/youtube.png"
            icon_active = "img/home/social/youtube_active.png"
            link = "https://www.youtube.com/user/iconem"

        [[params.home.social]]
            id = "vimeo"
            icon = "img/home/social/vimeo.png"
            icon_active = "img/home/social/vimeo_active.png"
            link = "https://vimeo.com/iconem"

        [[params.home.social]]
            id = "sketchfab"
            icon = "img/home/social/sketchfab.png"
            icon_active = "img/home/social/sketchfab_active.png"
            link = "https://sketchfab.com/iconem"


    # Projects section
    [params.projects]
    	title="Our mission/projects"
    	description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

   	# Projects modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Map section
    [params.map]
    	src="img/home/home_background.png"

	# About section
	[params.about]
		title    = "About"
		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
