title = "Iconem"
googleAnalytics = ""
DefaultContentLanguage = "en"
baseUrl = "iconem.com"

[languages]

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "img/favicons/favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Iconem"

		[languages.en.navigation.links]
			projects = "Projects"
			map  = "Map"
			about = "About"
			contact   = "Contact"
			language = "Language"

		[[languages.en.navigation.lang]]
			code = "fr"
			link = "/fr"

		[languages.fr.navigation.links]
			projects = "Projets"
			map  = "Carte"
			about = "À propos"
			contact   = "Contact"
			language = "Langue"

		[[languages.fr.navigation.lang]]
			code = "en"
			link = "/"

	# Home section
	[params.home]
		slogan     = "Explore human heritage"
		draw = "../img/home/home_draw.png"

		[[params.home.social]]
            id = "tumblr"
            icon = "../img/home/social/tumblr.png"
            icon_active = "../img/home/social/tumblr_active.png"
            link = "http://iconem.tumblr.com/"

		[[params.home.social]]
            id = "facebook"
            icon = "../img/home/social/facebook.png"
            icon_active = "../img/home/social/facebook_active.png"
            link = "https://fr-fr.facebook.com/Iconem.corp/"

        [[params.home.social]]
            id = "sketchfab"
            icon = "../img/home/social/sketchfab.png"
            icon_active = "../img/home/social/sketchfab_active.png"
            link = "https://sketchfab.com/iconem"

        [[params.home.social]]
            id = "twitter"
            icon = "../img/home/social/twitter.png"
            icon_active = "../img/home/social/twitter_active.png"
            link = "https://twitter.com/iconem"

        [[params.home.social]]
            id = "vimeo"
            icon = "../img/home/social/vimeo.png"
            icon_active = "../img/home/social/vimeo_active.png"
            link = "https://vimeo.com/iconem"

        [[params.home.social]]
            id = "youtube"
            icon = "../img/home/social/youtube.png"
            icon_active = "../img/home/social/youtube_active.png"
            link = "https://www.youtube.com/user/iconem"


    # Projects section
    [languages.en.projects]
    	title="Our mission/projects"
    	description = "Our world’s cultural heritage is threatened. Looting, urbanisation, mass tourism, armed conflict, and climate change damage and destroy irreplaceable sites where cultures emerged, languages developed, civilisations thrived. These imperilled heritage sites embody humanity’s rich cultural diversity. It is crucial that we document and preserve them now. Iconem’s mission is to further conservation of these endangered places by digitising them for exploration and study, today and tomorrow. Our expert team travels the globe, combining the largescale scanning capacity of drones and the photorealistic quality of 3D to create digital replicas of our most treasured places, record them for future generations, and champion them today."

    [languages.fr.projects]
    	title="Nos missions"
    	description = "Le patrimoine mondial est en danger. Le pillage, l’urbanisation, les conflits armés et le changement climatique endommagent et détruisent des sites irremplaçables où des cultures ont émergé, des langues se sont développées, des civilisations ont prospéré. Ces sites patrimoniaux mis en péril incarnent l’incroyable diversité culturelle de l’humanité. Il est essentiel que nous les documentions et les préservions maintenant. La mission d’Iconem est de contribuer à la conservation de ces endroits en danger en les numérisant pour l’exploration et l’étude, aujourd’hui et demain. Notre équipe expérimentée travaille à travers le monde, associant la capacité de scan à grand échelle des drones et le photoréalisme de la 3D afin de réaliser des doubles numériques des sites les plus précieux, afin d’assurer leur transmission aux générations futures et leur défense aujourd’hui."

   	# Projects modals
	[languages.en.projects.modal]
        pictures="Pictures"
        videos="Videos"
        models="3D Models"
        actors="Actors: "
        partners="Partners: "
	[languages.fr.projects.modal]
        pictures="Photos"
        videos="Vidéos"
        models="Modèles 3D"
        actors="Acteurs : "
        partners="Partenaires : "

    # Map section
    [params.map]

	# About section
	[languages.en.about]
		title    = "About"
		description = "Founded in 2013, Iconem is an innovative startup that specialises in the digitisation of endangered cultural heritage sites in 3D. We work with international organisations and companies, including UNESCO, the Aga Khan Trust for Culture, Microsoft, and the drone manufacturer Parrot, as well as the world class museums such as the Louvre. We design site-specific architectural 3D models; large-scale urban and rural 3D models; museum exhibitions; and training for local professionals."
		clients = "Clients"
		partners = "Partners"

	[languages.fr.about]
		title    = "À propos"
		description = "Fondée en 2013, Iconem est une startup innovante spécialisée en numérisation 3D des sites patrimoniaux. Nous travaillons avec des organisations internationales, des gouvernements et collectivités ou des musées d’envergure internationale tels que l’UNESCO, l’Agha Khan Trust for Culture, le Sultanat d’Oman, la Mairie de Paris ou le Musée du Louvre. Nous réalisons des modèles 3D de monuments, de patrimoine urbain ou rural à grand-échelle, des expositions immersives et des formations pour les professionnels."
		clients = "Clients"
		partners = "Partenaires"

	# Contact section
	[params.contact]
		title = "Contact"
		phone = "+33 (0)1 42 49 76 04"
		adress = "6 rue Jules Chaplain 75006 Paris, France"
		email = "contact@iconem.com"
		business_plan = "pdf/business_plan.pdf"
		press_kit = "pdf/press_kit.pdf"

	# Footer
	[params.footer]
		content = "@ 2018 Iconem All rights reserved"
