title = "Iconem"
googleAnalytics = ""
DefaultContentLanguage = "en"
#baseUrl = "https://iconem.com/en/"
baseUrl = "https://3d.iconem.com/_dev/site/en/"
#baseUrl = "http://localhost:1313/en/"
publishDir = "docs"

[languages]
	[languages.en]
	#baseUrl = "https://iconem.com/en/"
  baseUrl = "https://3d.iconem.com/_dev/site/en/"
  #baseUrl = "http://localhost:1313/en/"
	name = "Iconem"
	description = "Iconem's mission is to contribute to heritage conservation. By scanning threatened sites, we hope to facilitate their exploration and study, for today and tomorrow."

	[languages.fr]
	#baseUrl = "https://iconem.com/fr/"
  baseUrl = "https://3d.iconem.com/_dev/site/en/"
  #baseUrl = "http://localhost:1314/fr/"
	name = "Iconem"
	description = "La mission d'Iconem est de contribuer à la conservation de ces endroits menacés en les numérisant pour l'exploration et l'étude, aujourd'hui et demain."


[params]

	# The path must be relative to the static folder
	favicon = "img/favicons/favicon.ico"
	

	# Navigation
	[params.navigation]
		brand = "Iconem"

		[languages.en.navigation.links]
			projects = "Projects"
			map  = "Map"
			about = "About"
      contribute = "Contribute"
			contact   = "Contact"
			language = "Language"
      studio = "Studio"
      research = "Research"
      exploration = "Exploration"

		[[languages.en.navigation.lang]]
			code = "fr"
			link = "https://iconem.fr"

		[languages.fr.navigation.links]
			projects = "Projets"
			map  = "Carte"
			about = "À propos"
      contribute = "Contribuer"
			contact   = "Contact"
			language = "Langue"
      studio = "Studio"
      research = "Recherche"
      exploration = "Exploration"

		[[languages.fr.navigation.lang]]
			code = "en"
			link = "https://iconem.com"

	# Home section
	[params.home]
    slogan_research_prefix     = "Explore"
    slogan_studio_prefix     = "Experience"
    slogan     = " human heritage"
		logo_research = "img/home/logo_iconem_research.png"
    logo_studio = "img/home/logo_iconem_studio.png"

		[[params.home.social]]
            id = "tumblr"
            icon = "img/home/social/tumblr.png"
            icon_active = "img/home/social/tumblr_active.png"
            link = "http://iconem.tumblr.com/"

		[[params.home.social]]
            id = "facebook"
            icon = "img/home/social/facebook.png"
            icon_active = "img/home/social/facebook_active.png"
            link = "https://fr-fr.facebook.com/Iconem.corp/"

        [[params.home.social]]
            id = "sketchfab"
            icon = "img/home/social/sketchfab.png"
            icon_active = "img/home/social/sketchfab_active.png"
            link = "https://sketchfab.com/iconem"

        [[params.home.social]]
            id = "twitter"
            icon = "img/home/social/twitter.png"
            icon_active = "img/home/social/twitter_active.png"
            link = "https://twitter.com/iconem"

        [[params.home.social]]
            id = "vimeo"
            icon = "img/home/social/vimeo.png"
            icon_active = "img/home/social/vimeo_active.png"
            link = "https://vimeo.com/iconem"

        [[params.home.social]]
            id = "youtube"
            icon = "img/home/social/youtube.png"
            icon_active = "img/home/social/youtube_active.png"
            link = "https://www.youtube.com/user/iconem"

        [[params.home.social]]
            id = "linkedin"
            icon = "img/home/social/linkedin.png"
            icon_active = "img/home/social/linkedin_active.png"
            link = "https://fr.linkedin.com/company/iconem"


    # Projects section
    [languages.en.projects]
    	title="Projects"
    	description = "Our world’s cultural heritage is threatened. Looting, urbanisation, mass tourism, armed conflict, and climate change damage and destroy irreplaceable sites where cultures emerged, languages developed, civilisations thrived. These imperilled heritage sites embody humanity’s rich cultural diversity. It is crucial that we document and preserve them now. Iconem’s mission is to further conservation of these endangered places by digitising them for exploration and study, today and tomorrow. Our expert team travels the globe, combining the large-scale scanning capacity of drones and the photorealistic quality of 3D to create digital replicas of our most treasured places, record them for future generations, and champion them today."

    [languages.fr.projects]
    	title="Notre mission et nos projets"
    	description = "Le patrimoine mondial est en danger. Le pillage, l’urbanisation, les conflits armés et le changement climatique endommagent et détruisent des sites irremplaçables où des cultures ont émergé, des langues se sont développées, des civilisations ont prospéré. Ces sites patrimoniaux mis en péril incarnent l’incroyable diversité culturelle de l’humanité. Il est essentiel que nous les documentions et les préservions maintenant. La mission d’Iconem est de contribuer à la conservation de ces endroits menacés en les numérisant pour l’exploration et l’étude, aujourd’hui et demain. Notre équipe expérimentée travaille à travers le monde, associant la capacité de scan à grande échelle des drones et le photoréalisme de la 3D afin de réaliser des doubles numériques des sites les plus précieux, afin d’assurer leur transmission aux générations futures et leur défense aujourd’hui."

   	# Projects modals
	[languages.en.projects.modal]
        pictures="Pictures"
        videos="Videos"
        models="3D Models"
        actors="Actors: "
        partners="Partners: "
	[languages.fr.projects.modal]
        pictures="Photos"
        videos="Vidéos"
        models="Modèles 3D"
        actors="Acteurs : "
        partners="Partenaires : "

    # Map section
    [params.map]

	# About section
	[languages.en.about]
		title    = "About"
		description = "Founded in 2013, Iconem is an innovative startup that specialises in the digitisation of endangered cultural heritage sites in 3D. We work with international organisations, national governments, local authorities, and world class museums such as UNESCO, the Aga Khan Trust for Culture, the Sultanate of Oman, the City of Paris, and the Louvre. We design site-specific architectural 3D models; large-scale urban and rural 3D models; museum exhibitions; and training for local professionals."

	[languages.fr.about]
		title    = "À propos"
		description = "Fondée en 2013, Iconem est une startup innovante spécialisée en numérisation 3D des sites patrimoniaux. Nous travaillons avec des organisations internationales, des gouvernements et collectivités ou des musées d’envergure internationale tels que l’UNESCO, l’Aga Khan Trust for Culture, le Sultanat d’Oman, la Mairie de Paris ou le Musée du Louvre. Nous réalisons des modèles 3D de monuments, de patrimoine urbain ou rural à grand-échelle, des expositions immersives et des formations pour les professionnels."

  # Contribute section
	[languages.en.contribute]
		title    = "Contribute"
		description = "If you want to support our work, you can help us ! Send your digitised photographies of heritage sites all around the world to <a href=\"mailto:contact@iconem.com\">contact(@)iconem.com</a>. We will use the pictures within our photogrammetric process or as scientific archives in order to protect and preserve the memory of endangered heritage sites."

	[languages.fr.contribute]
		title    = "Contribuer"
		description = "Si vous souhaitez soutenir notre travail, vous pouvez nous aider ! Envoyez à <a href=\"mailto:contact@iconem.com\">contact(@)iconem.com</a> vos photographies numérisées de sites patrimoniaux du monde entier. Nous utiliserons vos photos comme matériau pour nos algorithmes de photogrammétrie ou comme archives scientifiques afin de protéger et préserver la mémoire de sites historiques menacés."

	# Contact section
	[params.contact]
		title = "Contact"
		phone = "+33 (0)1 42 49 76 04"
		adress = "6 rue Jules Chaplain 75006 Paris, France"
		email = "contact(@)iconem.com"

	[languages.en.brochure]
		title = "Download our brochure"
		pdf = "pdf/Iconem_EN.pdf"

	[languages.fr.brochure]
		title = "Téléchargez notre plaquette"
		pdf = "pdf/Iconem_FR.pdf"

	[languages.en.press_kit]
		title = "Press Contact: xg(@)iconem.com"
		pdf = "pdf/press_kit.pdf"

	[languages.fr.press_kit]
		title = "Contact Presse : xg(@)iconem.com"
		pdf = "pdf/press_kit.pdf"

	[languages.en.newsletter]
		title = "Subscribe to our newsletter"
		placeholder = "Email Adress"
		button_label = "Subscribe"
		link = "https://iconem.us12.list-manage.com/subscribe/post?u=749f610ff78ee22f7360e7b72&amp;id=6256e49fdb"
		input_name="b_749f610ff78ee22f7360e7b72_6256e49fdb"

	[languages.fr.newsletter]
		title = "Inscrivez-vous pour recevoir notre newsletter"
		placeholder = "Adresse Email"
		button_label = "Valider"
		link = "https://iconem.us12.list-manage.com/subscribe/post?u=749f610ff78ee22f7360e7b72&amp;id=d589848b1b"
		input_name="b_749f610ff78ee22f7360e7b72_d589848b1b"

	# Partners
	[params.partners]
		enabled = true
	[languages.en.partners]
		clients = "Clients"
		partners = "Partners"
	[languages.fr.partners]
		clients = "Clients"
		partners = "Partenaires"

	# Footer
	[params.footer]
		content = "© 2021 Iconem. All rights reserved."
