backend:
  name: git-gateway
  branch: new # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
site_url: https://radiant-zabaione-e92fa0.netlify.app/en/
media_folder: static/img
public_folder: /img
collections:
  - name: "projects"
    label: "Projects"
    folder: "data/projects/research"
    format: "json"
    extension: "json"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    identifier_field: modalID
    fields:
      - label: "modalID"
        name: "modalID"
        widget: "string"
      - label: "ThumbnailTitle"
        name: "thumbnailTitle"
        widget: "object"
        summary: "{{fields.en}}: {{fields.fr}}"
        fields:
          - label: "En"
            name: "en"
            widget: "string"
          - label: "Fr"
            name: "fr"
            widget: "string"
      - label: "thumbnailLocation"
        name: "thumbnailLocation"
        widget: "object"
        summary: "{{fields.en}}: {{fields.fr}}"
        fields:
          - label: "En"
            name: "en"
            widget: "string"
          - label: "Fr"
            name: "fr"
            widget: "string"
      - label: "thumbnailDate"
        name: "thumbnailDate"
        widget: "object"
        summary: "{{fields.en}}: {{fields.fr}}"
        fields:
          - label: "En"
            name: "en"
            widget: "string"
          - label: "Fr"
            name: "fr"
            widget: "string"
      - label: "thumbnail"
        name: "thumbnail"
        widget: "string"
      - label: "articleTitle"
        name: "articleTitle"
        widget: "object"
        summary: "{{fields.en}}: {{fields.fr}}"
        fields:
          - label: "En"
            name: "en"
            widget: "string"
          - label: "Fr"
            name: "fr"
            widget: "string"
      - label: "articleLocation"
        name: "articleLocation"
        widget: "object"
        summary: "{{fields.en}}: {{fields.fr}}"
        fields:
          - label: "En"
            name: "en"
            widget: "string"
          - label: "Fr"
            name: "fr"
            widget: "string"
      - label: "articleDate"
        name: "articleDate"
        widget: "object"
        summary: "{{fields.en}}: {{fields.fr}}"
        fields:
          - label: "En"
            name: "en"
            widget: "string"
          - label: "Fr"
            name: "fr"
            widget: "string"
      - label: "text"
        name: "text"
        widget: "object"
        summary: "{{fields.en}}: {{fields.fr}}"
        fields:
          - label: "En"
            name: "en"
            widget: "string"
          - label: "Fr"
            name: "fr"
            widget: "string"
      - label: "actors"
        name: "actors"
        widget: "object"
        summary: "{{fields.en}}: {{fields.fr}}"
        fields:
          - label: "En"
            name: "en"
            widget: "string"
          - label: "Fr"
            name: "fr"
            widget: "string"
      - label: "img"
        name: "img"
        widget: "list"
        summary: "{{fields.full}}}}"
        fields:
          - label: preview
            name: preview
            widget: string
          - label: full
            name: full
            widget: string
          - label: caption
            name: caption
            widget: object
            fields:
              - label: en
                name: en
                widget: string
              - label: fr
                name: fr
                widget: string
