backend:
  name: git-gateway
  branch: new # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "projects"
    label: "Projects"
    folder: "data/projects/research"
    format: "json"
    extension: "json"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    identifier_field: modalID
    fields:
      - label: "modalID"
        name: "modalID"
        widget: "string"
      - label: "ThumbnailTitle"
        name: "thumbnailTitle"
        widget: "object"
        summary: "{{fields.en}}: {{fields.fr}}"
        fields:
          - label: "En"
            name: "en"
            widget: "string"
          - label: "Fr"
            name: "fr"
            widget: "string"
